name: goodboy

description: A sample Flutter project with heart rate card.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
